Fixed an exception from crashing the program
Fixed an exception where attempting to delete a directory that was not empty would result in the program crashing because of a shellexceptions.DirectoryNotEmptyException

Example:
Traceback (most recent call last):
  File "/Users/username/Desktop/Project-Shell/rmdir.py", line 28, in run_command
    os.rmdir(path=directory_to_remove)  # Remove the directory
OSError: [Errno 66] Directory not empty: '__pycache__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 88, in <module>
    func(argsplit.process_string(COMMAND_INPUT))
  File "/Users/username/Desktop/Project-Shell/rmdir.py", line 30, in run_command
    raise DirectoryNotEmptyException
shellexceptions.DirectoryNotEmptyException

The program now handles the exception gracefully due to a fix in the indentation of the try-except blocks with the following result:
$ rmdir __pycache__
Directory is not empty.
$